Repository compsci-adl/website, pull requests merged in 2024-07, with the labels that each got.

#156 fix: Run actions in context of the base of the pull request
  .github/workflows/ci-dev-pr.yml
Labels: ci

#152 feat: Add tech stack tags to ProjectCard component
  src/app/open-source/FutureProjectCard.tsx
  src/app/open-source/ProjectCard.tsx
  src/app/open-source/page.tsx
  src/components/Tag.tsx
  src/constants/colours.ts
  src/constants/tech-stack.ts
  src/data/future-projects.ts
  src/data/projects.ts
Labels: enhancement, frontend

#153 fix: fixed text overflow in header and event cards
  src/app/(home)/page.tsx
  src/app/contact/Contact.tsx
  src/app/contact/Sponsorship.tsx
  src/app/events/Events.tsx
  src/components/Header/HeaderClient.tsx
  src/components/Paragraph.tsx
  src/components/Title.tsx
  tailwind.config.ts
Labels: enhancement, frontend

#157 chore: added events for semester 2
  public/images/events/git-and-github-workshop.png
  public/images/events/meet-and-greet-s2.png
  public/images/events/pub-crawl.png
  src/data/events.ts
Labels: enhancement, frontend

#162 feat(events): Add Inter-University Beginner Competition
  public/images/events/beginner-competition.png
  src/data/events.ts
Labels: events
