Repository compsci-adl/website, pull requests merged in 2024-05, with the labels that each got.

#141 feat: Add open source page
  public/images/projects/duckbot.png
  public/images/projects/website.png
  src/app/open-source/ProjectCard.tsx
  src/app/open-source/page.tsx
  src/components/Button.tsx
  src/components/Header/components/Links.tsx
  src/data/projects.ts
Labels: frontend

#144 ci: Add Docker and workflows for deploying to AWS
  .dockerignore
  .github/workflows/build_and_test.yml
  .github/workflows/ci-dev-pr.yml
  .github/workflows/ci-dev.yml
  .github/workflows/lint-and-format.yml
  .github/workflows/production.yml
  Dockerfile
  docker-compose.yml
  pnpm-lock.yaml
Labels: ci

#145 chore: migrate Clerk to v5 and fix middleware issue
  .env.local.example
  Dockerfile
  package.json
  pnpm-lock.yaml
  public/ducks.txt
  public/humans.txt
  public/robots.txt
  src/app/(account)/join/page.tsx
  src/app/(account)/settings/page.tsx
  src/app/(account)/signin/page.tsx
  src/app/admin/page.tsx
  src/app/api/member/route.ts
  src/app/api/payment/route.ts
  src/app/layout.tsx
  src/components/Header/index.tsx
  src/env.mjs
  src/middleware.ts
Labels: enhancement
