Repository compsci-adl/website, pull requests merged in 2024-02, with the labels that each got.

#46 feat: Add payment functionality
  .env.local.example
  CONTRIBUTING.md
  docs/redis.md
  docs/square.md
  package.json
  pnpm-lock.yaml
  src/app/(account)/join/ProgressBar.tsx
  src/app/(account)/join/page.tsx
  src/app/(account)/join/steps/StepFour.tsx
  src/app/(account)/join/steps/StepOne.tsx
  src/app/(account)/join/steps/StepThree.tsx
  src/app/(account)/join/steps/StepTwo.tsx
  src/app/(account)/join/store.ts
  src/app/(account)/signin/page.tsx
  src/app/api/member/route.ts
  src/app/api/payment/route.ts
  src/app/api/verify-membership-payment/route.ts
  src/components/Header.tsx
  src/data/products.ts
  src/env.mjs
  src/lib/fetcher.ts
  src/lib/redis.ts
  src/lib/square.ts
  src/middleware.ts
  tsconfig.json
Labels: enhancement, backend

#44 feat: Add about us page
  public/images/about/ai-panel.jpg
  public/images/about/cocktail-night.jpg
  public/images/about/duck-ctf-2.jpg
  public/images/about/duck-ctf.jpg
  public/images/about/meet-and-greet.jpg
  public/images/about/o-week.jpg
  public/images/about/quiz-night.jpg
  public/images/about/women-in-cs.jpg
  public/images/rectangle-grid.svg
  public/images/white-star-outline.svg
  public/images/white-star.svg
  src/app/(home)/page.tsx
  src/app/about/FAQ.tsx
  src/app/about/page.tsx
  src/components/Ducks.tsx
  src/components/FancyRectangle.tsx
  src/components/Header.tsx
  src/data/committeeMembers.ts
Labels: frontend

#48 fix(header): Mobile menu closes as expected
  src/components/Header.tsx
  src/constants/breakpoints.ts
Labels: bug

#49 feat: Add settings page
  package.json
  pnpm-lock.yaml
  src/app/(account)/join/steps/StepFour.tsx
  src/app/(account)/join/steps/StepTwo.tsx
  src/app/(account)/settings/Settings.tsx
  src/app/(account)/settings/Sidebar.tsx
  src/app/(account)/settings/page.tsx
  src/app/(account)/settings/tabs/AccountSettings.tsx
  src/app/(account)/settings/tabs/MembershipSettings.tsx
  src/app/(account)/settings/tabs/NotificationsSettings.tsx
  src/app/(account)/settings/tabs/PersonalInfoSettings.tsx
  src/app/api/check-user-exists/route.ts
  src/app/api/member/route.ts
  src/app/api/payment/route.ts
  src/app/api/verify-membership-payment/route.ts
  src/components/Button.tsx
  src/components/Field.tsx
  src/components/Header.tsx
  src/components/UserButton.tsx
  src/constants/colours.ts
  src/db/queries.ts
  src/db/schema.ts
  src/lib/fetcher.ts
  src/utils/format-date.ts
Labels: frontend, backend, priority:high

#57 fix: Membership setting doesn't change after payment
  src/app/(account)/settings/page.tsx
  src/app/api/payment/route.ts
Labels: frontend, backend, priority:high

#59 feat: Add admin panel
  README.md
  docs/clerk.md
  package.json
  pnpm-lock.yaml
  src/app/(account)/settings/page.tsx
  src/app/admin/MemberForm.tsx
  src/app/admin/page.tsx
  src/app/api/payment/route.ts
  src/components/Autocomplete.tsx
  src/components/UserButton.tsx
  src/db/index.ts
  src/db/queries.ts
  src/db/schema.ts
  src/middleware.ts
Labels: frontend, backend, priority:high

#61 fix(admin): Minor fix
  src/app/(account)/settings/page.tsx
  src/app/admin/MemberForm.tsx
Labels: bug, frontend, backend, priority:high

#63 feat: Add drive link
  .env.local.example
  src/app/(account)/settings/Settings.tsx
  src/app/(account)/settings/page.tsx
  src/app/api/payment/route.ts
  src/app/api/user-existence/route.ts
  src/components/Header.tsx
  src/components/UserButton.tsx
  src/env.mjs
  src/server/check-user-exists.ts
  src/server/update-member-expiry-date.ts
  src/server/verify-membership-payment.ts
Labels: priority:high

#64 fix: Header buttons
  src/app/(account)/signin/page.tsx
  src/components/Header.tsx
Labels: bug, frontend, priority:high

#79 fix(payment): use paymentId to determine if payment complete
  src/server/verify-membership-payment.ts
Labels: bug

#89 feat: add button loading to indicate request in progress
  src/app/(account)/forgot-password/page.tsx
  src/app/(account)/join/steps/StepOne.tsx
  src/app/(account)/signin/page.tsx
Labels: enhancement

#96 fix(header): mobile menu has correct links and behaviour
  src/components/Header/HeaderClient.tsx
  src/components/Header/HeaderMobileClient.tsx
  src/components/Header/components/Links.tsx
  src/components/Header/components/SignInJoin.tsx
Labels: bug

#100 fix(contact): minor fix for mobile style
  src/app/contact/Form.tsx
  src/app/contact/Sponsorship.tsx
Labels: bug

#104 chore: Improve mobile responsiveness
  src/app/(account)/forgot-password/page.tsx
  src/app/(account)/join/page.tsx
  src/app/(account)/join/steps/StepFour.tsx
  src/app/(account)/join/steps/StepOne.tsx
  src/app/(account)/join/steps/StepThree.tsx
  src/app/(account)/join/steps/StepTwo.tsx
  src/app/(account)/settings/Settings.tsx
  src/app/(account)/settings/Sidebar.tsx
  src/app/(account)/settings/page.tsx
  src/app/(account)/settings/tabs/AccountSettings.tsx
  src/app/(account)/settings/tabs/MembershipSettings.tsx
  src/app/(account)/settings/tabs/NotificationsSettings.tsx
  src/app/(account)/settings/tabs/PersonalInfoSettings.tsx
  src/app/(account)/signin/page.tsx
  src/app/(home)/page.tsx
  src/app/about/FAQ.tsx
  src/app/about/page.tsx
  src/app/events/FridayNight.tsx
  src/app/events/Info.tsx
  src/components/Button.tsx
  src/components/FancyRectangle.tsx
  src/components/Link.tsx
Labels: enhancement, frontend
