Repository compsci-adl/website, pull requests merged in 2024-08, with the labels that each got.

#164 feat: add a button on open source page linking to the signup form
  src/app/open-source/page.tsx
Labels: enhancement

#170 Update Tech Stack on open source page
  src/constants/colours.ts
  src/constants/tech-stack.ts
  src/data/future-projects.ts
Labels: enhancement, frontend

#171 feat(events): Add Clubsland event
  public/images/events/clubsland.png
  src/data/events.ts
Labels: frontend

#176 feat(events): Add Pandas workshop event
  public/images/events/pandas-workshop.png
  src/data/events.ts
Labels: events

#178 feat(events): Add intro to ctf workshop
  public/images/events/ctf-workshop.png
  src/data/events.ts
Labels: events

#179 fix: Set timezone for end time and dynamically calculate event end
  package.json
  pnpm-lock.yaml
  src/app/events/Events.tsx
  src/data/events.ts
Labels: fix

#180 feat(events): Add DuckCTF event
  public/images/events/duck-ctf.png
  src/data/events.ts
Labels: events

#182 feat: Add upcoming events to the home page
  src/app/(home)/UpcomingEventCard.tsx
  src/app/(home)/page.tsx
Labels: enhancement

#183 build(ci): Use Github runner for production build
  .github/workflows/production.yml
Labels: ci
