Repository compsci-adl/website, pull requests merged in 2024-01, with the labels that each got.

#10 Optimise form with `react-hook-form`
  next.config.js
  package.json
  pnpm-lock.yaml
  src/app/(account)/sign-in/page.tsx
  src/components/Button.tsx
  src/components/ControlledField.tsx
  src/components/Field.tsx
  src/components/UserButton.tsx
  src/middleware.ts
Labels: enhancement

#14 Account system (part)
  .env.local.example
  next.config.js
  package.json
  pnpm-lock.yaml
  public/images/greyDuckOutline.svg
  public/images/yellowDuck.svg
  src/app/(account)/forgot-password/page.tsx
  src/app/(account)/helpers.ts
  src/app/(account)/join-us/ProgressBar.tsx
  src/app/(account)/join-us/page.tsx
  src/app/(account)/join-us/steps/StepFour.tsx
  src/app/(account)/join-us/steps/StepOne.tsx
  src/app/(account)/join-us/steps/StepThree.tsx
  src/app/(account)/join-us/steps/StepTwo.tsx
  src/app/(account)/join-us/store.ts
  src/app/(account)/layout.tsx
  src/app/(account)/schemas.ts
  src/app/(account)/sign-in/page.tsx
  src/app/(home)/page.tsx
  src/app/layout.tsx
  src/app/not-found.tsx
  src/components/Button.tsx
  src/components/ControlledField.tsx
  src/components/Field.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/UserButton.tsx
  src/hooks/use-mount.ts
  src/middleware.ts
  tailwind.config.ts
Labels: frontend, backend, priority:high

#28 Add issue and PR templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/pull_request_template.yml
Labels: documentation, priority:normal

#27 Add env management
  .eslintrc.cjs
  next.config.js
  next.config.mjs
  package.json
  pnpm-lock.yaml
  src/env.mjs
Labels: enhancement, priority:normal

#30 Add contacts page
  package.json
  pnpm-lock.yaml
  public/images/crosses.svg
  src/app/(account)/layout.tsx
  src/app/(home)/layout.tsx
  src/app/(home)/page.tsx
  src/app/contact/Contact.tsx
  src/app/contact/Form.tsx
  src/app/contact/Sponsorship.tsx
  src/app/contact/page.tsx
  src/app/layout.tsx
  src/components/Button.tsx
  src/components/FancyRectangle.tsx
  src/components/Footer.tsx
  src/components/Link.tsx
  src/components/Paragraph.tsx
  src/components/Title.tsx
  src/constants/colours.ts
  src/data/links.ts
  src/util/links.ts
Labels: frontend, priority:normal

#33 Convert `a` to nextjs `link`
  src/app/(account)/join-us/page.tsx
  src/app/(account)/join-us/steps/StepOne.tsx
  src/app/(account)/sign-in/page.tsx
  src/components/Header.tsx
  src/components/UserButton.tsx
Labels: bug, frontend

#35 Reuse page height and top padding in layout
  src/app/(account)/forgot-password/page.tsx
  src/app/(account)/join-us/page.tsx
  src/app/(account)/sign-in/page.tsx
  src/app/(home)/page.tsx
  src/app/contact/Form.tsx
  src/app/contact/page.tsx
  src/app/layout.tsx
  src/app/not-found.tsx
  src/components/Footer.tsx
  src/components/Link.tsx
  src/components/Paragraph.tsx
  src/components/Title.tsx
Labels: frontend, refactor

#37 Add backend
  .env.local.example
  .gitignore
  README.md
  drizzle.config.ts
  package.json
  pnpm-lock.yaml
  src/app/(account)/join-us/steps/StepFour.tsx
  src/app/(account)/join-us/steps/StepThree.tsx
  src/app/(account)/join-us/steps/StepTwo.tsx
  src/app/api/member/route.ts
  src/constants/student-info.ts
  src/db/index.ts
  src/db/schema.ts
  src/env.mjs
  src/utils/fetcher.ts
  tsconfig.json
Labels: enhancement, backend

#38 Add Contributing Guidelines
  CONTRIBUTING.md
  LICENSE
  README.md
Labels: documentation

#39 refactor: Rename all images to dash-case
  public/images/grey-duck-outline.svg
  public/images/home/cyber-panel.jpg
  public/images/home/duck-ctf.jpg
  public/images/home/pizza.jpg
  public/images/logos/logo-text.svg
  public/images/logos/logo.png
  public/images/logos/logo.svg
  public/images/rectangle-grid.svg
  public/images/square-grid.svg
  public/images/white-duck-outline.svg
  public/images/white-duck.svg
  public/images/yellow-duck.svg
  public/images/yellow-star.svg
  public/images/yellow-triangle.svg
  src/app/(account)/join-us/ProgressBar.tsx
  src/app/(home)/ImageCarousel.tsx
  src/app/(home)/page.tsx
  src/app/contact/Form.tsx
  src/app/contact/page.tsx
  src/components/Header.tsx
Labels: enhancement, frontend, refactor

#40 feat: Add sponsors page
  public/images/sponsors/atlassian.svg
  public/images/sponsors/boeing.svg
  public/images/sponsors/jane-street.png
  public/images/sponsors/level-star/bronze.svg
  public/images/sponsors/level-star/gold.svg
  public/images/sponsors/level-star/silver.svg
  public/images/sponsors/macquarie.svg
  public/images/sponsors/pricewaterhouse-coopers.svg
  public/images/sponsors/vivcourt.svg
  src/app/(account)/join-us/steps/StepOne.tsx
  src/app/(home)/page.tsx
  src/app/contact/Sponsorship.tsx
  src/app/sponsors/Sponsors.tsx
  src/app/sponsors/page.tsx
  src/components/FancyRectangle.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/Link.tsx
  src/components/Title.tsx
  src/data/sponsors.ts
Labels: enhancement, frontend

#45 fix(sponsors): use correct file name
  src/data/sponsors.ts
Labels: bug
